# Generated by Django 3.1.4 on 2020-12-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=16, verbose_name='Откуда')),
                ('Where', models.CharField(max_length=16, verbose_name='Куда')),
                ('Since', models.CharField(max_length=10, verbose_name='С какого')),
                ('To', models.CharField(max_length=10, verbose_name='По какое')),
            ],
        ),
    ]
