# Generated by Django 3.1.4 on 2020-12-27 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='Since',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='To',
        ),
        migrations.AddField(
            model_name='tickets',
            name='Carrier',
            field=models.CharField(default='', max_length=10, verbose_name='Перевозчик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now, max_length=10, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
